<a href="https://colab.research.google.com/github/jyothsnabankuru6-cyber/AI-Powered-Soil-Analytics/blob/main/AI_Powered_Soil_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!unzip -o archive.zip

Archive:  archive.zip
  inflating: crop_fertilizer_recommendation_dataset.csv

In [2]:
import pandas as pd

df = pd.read_csv("crop_fertilizer_recommendation_dataset.csv")

df.head()

,N,P,K,temperature,humidity,ph,rainfall,label,fertilizer,N_status,P_status,K_status,recommendation_note
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,Balanced NPK (14-14-14),Normal,Normal,Normal,Based on NPK + climate conditions
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,Balanced NPK (14-14-14),Normal,Normal,Normal,Based on NPK + climate conditions
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,Balanced NPK (14-14-14),Normal,Normal,Normal,Based on NPK + climate conditions
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,DAP (Diammonium Phosphate),Normal,Low,Normal,Based on NPK + climate conditions
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,Balanced NPK (14-14-14),Normal,Normal,Normal,Based on NPK + climate conditions

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 2200
Number of columns: 13

In [4]:
print(df.columns.tolist())

['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label', 'fertilizer', 'N_status', 'P_status', 'K_status', 'recommendation_note']

In [5]:
df.isnull().sum()

N                      0
P                      0
K                      0
temperature            0
humidity               0
ph                     0
rainfall               0
label                  0
fertilizer             0
N_status               0
P_status               0
K_status               0
recommendation_note    0
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [7]:
df.dtypes

N                        int64
P                        int64
K                        int64
temperature            float64
humidity               float64
ph                     float64
rainfall               float64
label                   object
fertilizer              object
N_status                object
P_status                object
K_status                object
recommendation_note     object
dtype: object

In [8]:
df.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [9]:
print("Number of crop classes:", df["label"].nunique())
print("\nCrop distribution:")
print(df["label"].value_counts())

Number of crop classes: 22

Crop distribution:
label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [10]:
print("Number of fertilizer categories:", df["fertilizer"].nunique())
print("\nFertilizer distribution:")
print(df["fertilizer"].value_counts())

Number of fertilizer categories: 5

Fertilizer distribution:
fertilizer
Urea (Nitrogen rich fertilizer)    914
Balanced NPK (10-26-26)            378
DAP (Diammonium Phosphate)         371
MOP (Muriate of Potash)            274
Balanced NPK (14-14-14)            263
Name: count, dtype: int64

In [11]:
print(df["recommendation_note"].value_counts())

recommendation_note
Based on NPK + climate conditions    2200
Name: count, dtype: int64

In [12]:
print("Nitrogen Status:")
print(df["N_status"].value_counts())

print("\nPhosphorus Status:")
print(df["P_status"].value_counts())

print("\nPotassium Status:")
print(df["K_status"].value_counts())

Nitrogen Status:
N_status
Low       1292
Normal     614
High       294
Name: count, dtype: int64

Phosphorus Status:
P_status
Normal    1192
Low        808
High       200
Name: count, dtype: int64

Potassium Status:
K_status
Low       1335
Normal     665
High       200
Name: count, dtype: int64

In [13]:
print("Negative N values:", (df["N"] < 0).sum())
print("Negative P values:", (df["P"] < 0).sum())
print("Negative K values:", (df["K"] < 0).sum())
print("Invalid pH values:", ((df["ph"] < 0) | (df["ph"] > 14)).sum())
print("Invalid humidity values:", ((df["humidity"] < 0) | (df["humidity"] > 100)).sum())

Negative N values: 0
Negative P values: 0
Negative K values: 0
Invalid pH values: 0
Invalid humidity values: 0

In [14]:
numeric_columns = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((df[column] < lower) | (df[column] > upper)).sum()

    print(column, ":", outliers, "outliers")

N : 0 outliers
P : 138 outliers
K : 200 outliers
temperature : 86 outliers
humidity : 30 outliers
ph : 57 outliers
rainfall : 100 outliers

In [15]:
df.groupby("label")[["N", "P", "K", "ph"]].mean().round(2)

                  N       P       K    ph
label
apple         20.80  134.22  199.89  5.93
banana       100.23   82.01   50.05  5.98
blackgram     40.02   67.47   19.24  7.13
chickpea      40.09   67.79   79.92  7.34
coconut       21.98   16.93   30.59  5.98
coffee       101.20   28.74   29.94  6.79
cotton       117.77   46.24   19.56  6.91
grapes        23.18  132.53  200.11  6.03
jute          78.40   46.86   39.99  6.73
kidneybeans   20.75   67.54   20.05  5.75
lentil        18.77   68.36   19.41  6.93
maize         77.76   48.44   19.79  6.25
mango         20.07   27.18   29.92  5.77
mothbeans     21.44   48.01   20.23  6.83
mungbean      20.99   47.28   19.87  6.72
muskmelon    100.32   17.72   50.08  6.36
orange        19.58   16.55   10.01  7.02
papaya        49.88   59.05   50.04  6.74
pigeonpeas    20.73   67.73   20.29  5.79
pomegranate   18.87   18.75   40.21  6.43
rice          79.89   47.58   39.87  6.43
watermelon    99.42   17.00   50.22  6.50